Retrying workflow #7

diff --git a/.github/workflows/docs_gh_page.yml b/.github/workflows/docs_gh_page.yml
--- a/.github/workflows/docs_gh_page.yml
+++ b/.github/workflows/docs_gh_page.yml
@@ -7,21 +7,74 @@ on:
 jobs:
   docs_gh_page:
     runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{  secrets.GITHUB_TOKEN }}
 
     steps:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Deploy
-        uses: peterhs73/sphinx-docs-action@v0.0.1
+      - name: Set up Python
+        uses: actions/setup-python@v4
         with:
-          python-version: 3.10 
-          pyproject-path: pyproject.toml # defaults to pyproject.toml
-          docs-source: docs/ # defaults to docs/
-          docs-build: docs_build/ # defaults to docs_build/
-          external-repo: <username>/<repo-name>
-          external-repo-branch: gh-pages # defaults to master
-          deploy-token: ${{ secrets.PRIVATE_TOKEN}}
+          python-version: '3.10'
+      
+      - name: Install Poetry
+        uses: snok/install-poetry@v1
+        with:
+          virtualenvs-create: true
+          virtualenvs-in-project: true
+          installer-parallel: true
+          
+
+      - name: Install dependencies
+        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
+        run: poetry install --no-interaction --no-root
+      #----------------------------------------------
+      # install your root project, if required
+      #----------------------------------------------
+
+      - name: Install dependencies
+        run: |
+          source .venv/bin/activate
+          poetry add sphinx
+          poetry add sphinx-rtd-theme
+
+ 
+    
+      # Standard drop-in approach that should work for most people.
+      - uses: ammaraskar/sphinx-action@master
+        with:
+          docs-folder: "docs/"
+
+
+      # Great extra actions to compose with:
+      # Create an artifact of the html output.
+      - uses: actions/upload-artifact@v1
+        with:
+          name: DocumentationHTML
+          path: docs/_build/html/
+    
+      # Publish built docs to gh-pages branch.
+      # ===============================
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/ktomi96/mvm_smart_metering.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/_build/html/* gh-pages/
+          cd gh-pages
+          touch .nojekyll
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Publish PyPi package
         uses: code-specialist/pypi-poetry-publish@v1
